# Generated by Django 4.2.9 on 2024-01-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default=12, upload_to=''),
            preserve_default=False,
        ),
    ]
