# Generated by Django 4.2.9 on 2024-01-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movies_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='img',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
